// Spoken narration for the column components and the eight modes, at two levels:
// "general" for a broad audience and "physics" for the instrument physics behind it,
// in a female or a male voice. Scripts are written for the ear (no symbols or subscripts)
// and kept fixed, so pre-generated clips in audio/narration/<voice>/<level>/<slug>.mp3 always
// match. If a clip is missing, the browser's own speech synthesis reads the same script.

export const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const GENERAL = {
  // ---------------------------------------------------------------- modes
  'mode-tem': `Transmission electron microscopy. A broad, parallel electron wave floods the specimen. Atoms barely absorb electrons. Instead, they shift the phase of the wave passing through them. The objective lens turns those invisible phase shifts into light and dark, by recombining scattered and unscattered waves with a small, deliberate defocus. So the dots you see are interference fringes, not photographs of atoms. Change the focus, and black can swap for white. The panel on the right is the image's Fourier transform. Its rings, called Thon rings, are the fingerprint of the lens.`,
  'mode-stem': `Scanning transmission electron microscopy. The lenses squeeze the beam into a needle about one ångström wide, and raster it across the sample, point by point. At each point, detectors count what comes out. The ring-shaped high-angle annular dark-field detector catches electrons flung outward by close passes to the nucleus. That signal grows roughly as the atomic number to the power of one point seven, so brightness reads almost directly as atomic number. Gold blazes. Carbon nearly vanishes.`,
  'mode-4d': `Four-dimensional STEM. Instead of summing electrons on a fixed ring, a direct electron detector, running at thousands of frames per second, records the entire diffraction pattern at every probe position. That is two scan axes times two detector axes. Detectors are now designed afterwards, in software. Differential phase contrast and centre-of-mass imaging track how each atom's electric field nudges the beam sideways. Ptychography goes further, solving for the specimen's full phase from the overlapping patterns. And multislice ptychography slices the specimen in depth, recovering what single-slice methods blur together.`,
  'mode-diff': `Selected-area electron diffraction. The lower lenses are refocused from the image to the back focal plane of the objective, where every electron leaving the sample in the same direction lands on the same point. A crystal only scatters into Bragg directions, so it prints a lattice of spots. Many randomly oriented crystals print rings. The distance of each spot from the centre gives the spacing between atomic planes directly. The faint straight bands are Kikuchi lines. They are locked to the crystal, and swing as you tilt it.`,
  'mode-cbed': `Convergent-beam electron diffraction. Instead of a parallel beam, a cone of electrons is focused onto one small spot, so each Bragg reflection spreads into a disk. Inside those disks, intensity oscillates as electrons scatter back and forth between beams, and the spacing of those fringes measures the specimen's thickness to a few nanometres. Fine dark lines from higher-order Laue zones shift with tiny changes in lattice parameter, so CBED is used to map strain. Large-angle CBED widens the view, and its lines break where they cross a grain boundary.`,
  'mode-eds': `Energy-dispersive X-ray spectroscopy. When a fast electron knocks out an inner-shell electron, an outer electron drops into the hole and the atom emits an X-ray with an energy unique to that element. A silicon drift detector beside the specimen counts these photons and sorts them by energy. Each peak names an element, and its height tells you how much is there. Scan the probe, and every pixel gets its own spectrum, giving chemical maps at near-atomic resolution. Click a peak to map that element.`,
  'mode-eels': `Electron energy-loss spectroscopy. After the sample, a magnetic prism bends the beam, and slower electrons bend more, spreading the beam into a spectrum of energy lost. The tall zero-loss peak is electrons that lost nothing. The broad hump a few tens of electron volts away is the plasmon, a collective oscillation of the valence electrons. Further out, sharp edges mark inner-shell ionisation, a fingerprint of each element, and their fine structure reveals bonding and oxidation state. Drag the window across the spectrum to map a single edge.`,
  'mode-ronch': `The Ronchigram, and aberration correction. With the beam focused on thin amorphous carbon and the image of the probe's diffraction plane on the camera, the lens's aberrations become visible as distortions in a shadow image. At the centre lies a smooth, flat region where the electron wave's phase stays within a quarter wavelength. That flat patch sets the largest usable convergence angle, and therefore the smallest probe. Adjust the corrector's coefficients, defocus, astigmatism, coma and spherical aberration, to grow the flat region, or press auto-tune and watch the corrector do it.`,

  // ---------------------------------------------------------------- components
  'Electron gun': `The electron gun. A Schottky field-emission tip, a sharp tungsten crystal coated with zirconium oxide and heated to about eighteen hundred kelvin, emits electrons from a virtual source only fifteen nanometres across. Its brightness decides how much current can be packed into an atom-sized probe, and its energy spread, under one electron volt, sets the chromatic limit on resolution. Cold field emitters trade stability for an even narrower energy spread.`,
  'High-voltage accelerator': `The high-voltage accelerator. A stack of electrodes accelerates the electrons to their working voltage, up to three hundred kilovolts. At that energy they travel at seventy-eight percent of the speed of light, with a wavelength of about two picometres. The voltage must be stable to better than one part per million, because any ripple blurs the image just like the gun's own energy spread.`,
  'Condenser lens 1': `The first condenser lens. It demagnifies the image of the source, a setting called the spot size. A stronger lens makes a smaller source image, with less current but more coherence. Like every lens here, it is a copper coil in a soft iron yoke, focusing electrons with a magnetic field, and spinning the image as they spiral through.`,
  'Condenser lens 2': `The second condenser lens. It decides how the beam arrives at the specimen: as a broad, parallel wave for imaging and diffraction, or as a tight converging cone focused to a probe for scanning work.`,
  'Condenser aperture': `The condenser aperture. A small hole in a metal strip that trims the beam. In scanning mode it sets the convergence angle of the probe, and so the balance between diffraction blur, which favours a big aperture, and lens aberrations, which favour a small one.`,
  'Aberration corrector': `The aberration corrector. Round magnetic lenses always suffer from positive spherical aberration: rays far from the axis focus too strongly. A corrector, built from multipole lenses such as hexapoles, introduces a compensating negative aberration. That one idea took electron microscopes from about two ångströms to below half an ångström, and earned the pioneers the Kavli Prize.`,
  'Scan coils': `The scan coils. Two pairs of deflection coils tilt the beam and then tilt it back, so it shifts across the specimen while still passing through the lens's pivot point. In scanning mode they raster the probe line by line. Their calibration, and how fast they settle at the start of each line, decide the accuracy of every distance you measure.`,
  'Objective lens': `The objective lens, the heart of the microscope. The specimen sits inside its pole-piece gap, in a field of about two tesla. Every image detail passes through this lens first, so its spherical and chromatic aberrations, and how it transfers each spatial frequency, set the resolution of the whole instrument.`,
  'EDS X-ray detector': `The energy-dispersive X-ray detector. A silicon drift detector, angled toward the specimen, catches characteristic X-rays and measures each photon's energy. The larger the solid angle it covers, the more of the rare X-ray events it collects, which is why modern instruments surround the sample with several detectors.`,
  'Objective aperture': `The objective aperture. It sits in the back focal plane and selects which scattered beams form the image. A small aperture around the central beam gives bright-field contrast. Shifting it onto a single diffracted beam gives a dark-field image, lighting up only the crystals that diffract into it.`,
  'Back focal plane': `The back focal plane. Here, every electron leaving the specimen in the same direction meets at the same point, so this plane holds the diffraction pattern. Switching between imaging and diffraction simply means telling the lower lenses which plane to magnify: the image plane, or this one.`,
  'Selected-area aperture': `The selected-area aperture. Placed in an image plane, it picks out a region of the specimen, so the diffraction pattern comes only from that region. It is how you get a pattern from one grain, without its neighbours.`,
  'Intermediate lens': `The intermediate lens. By changing its strength, the microscope chooses whether the projector system magnifies the image or the diffraction pattern, and sets the magnification or camera length.`,
  'Projector lens': `The projector lens. The final lens enlarges the image or pattern onto the screen or camera, with total magnifications from a few hundred to several million times.`,
  'Fluorescent screen': `The fluorescent screen. A layer of phosphor glows green where electrons strike, for viewing by eye. It swings up out of the way whenever a camera or detector below it is in use.`,
  'Annular dark-field detector': `The annular dark-field detector. A ring-shaped scintillator collects electrons scattered to high angles. Because that scattering grows strongly with atomic number, the image shows heavy atoms bright and light atoms dim, with little sensitivity to focus or thickness.`,
  'Bright-field detector': `The bright-field detector. A small disk on the axis collects electrons that pass through with little deflection. Its images resemble conventional transmission images, and an annular version, the annular bright-field detector, can reveal light atoms such as oxygen and lithium.`,
  'Direct electron detector': `The direct electron detector. Instead of converting electrons to light, each electron is detected directly in a thin silicon sensor, and counted individually. Running at thousands of frames per second, it records full diffraction patterns at every scan position, which makes four-dimensional STEM and ptychography possible.`,
  'Magnetic prism': `The magnetic prism. A uniform magnetic field bends the beam through ninety degrees or more. Electrons that lost energy in the specimen are slower, so they bend more, spreading the beam into an energy-loss spectrum with a resolution set by the gun's energy spread.`,
  'Energy-loss spectrum': `The energy-loss spectrum. Read from left to right: the zero-loss peak, the plasmon, and then the core-loss edges of each element. With a monochromator, modern instruments resolve energy losses of a few millielectron volts, enough to measure atomic vibrations.`,
};

const PHYSICS = {
  // ---------------------------------------------------------------- modes
  'mode-tem': `Phase-contrast imaging, in more depth. For a thin specimen, the exit wave is the incident plane wave multiplied by a phase factor: the interaction constant, sigma, times the projected electrostatic potential. That is the weak phase object approximation. The objective lens then multiplies the wave, in reciprocal space, by a phase factor of minus i chi, where chi is the aberration function: pi times lambda times defocus times k squared, plus one half pi times C-s times lambda cubed times k to the fourth. For a weak phase object, the image is the projected potential filtered by sine chi, the phase contrast transfer function. At Scherzer defocus, sine chi stays near minus one over a broad band, out to the point resolution, about two thirds of C-s to the quarter times lambda to the three quarters. Beyond that, the temporal-coherence envelope, set by the focal spread from chromatic aberration, damps transfer exponentially in k to the fourth, and defines the information limit. The dark Thon rings in the diffractogram are the zeros of sine chi.`,
  'mode-stem': `Scanning transmission, in more depth. The probe is the inverse Fourier transform of the condenser aperture function times the aberration phase factor. Its diffraction-limited size scales as lambda over alpha, while spherical aberration blurs it as C-s times alpha cubed, so without a corrector the best convergence angle scales as lambda over C-s, to the one quarter. A high-angle annular detector integrates over a large range of angles that includes thermal diffuse scattering. That destroys the transverse coherence, and the image becomes incoherent: the probe intensity convolved with an object function. Unscreened Rutherford scattering would go as Z squared; screening by the atomic electrons reduces the exponent to between about one point six and two. Along a zone axis, the probe channels down the atomic columns, so intensity also depends on thickness and on the probe's focus within the crystal. By the reciprocity theorem, a small on-axis bright-field detector gives the same coherent image as conventional TEM.`,
  'mode-4d': `Four-dimensional STEM, in more depth. Each recorded pattern is the squared modulus of the Fourier transform of the probe times the specimen transmission function, at one probe position. For a thin specimen, Ehrenfest's theorem says the centre of mass of each pattern measures the average gradient of the projected potential within the probe, that is, the in-plane electric field. Integrating that vector field gives the potential itself. Segmented differential phase contrast is a coarse approximation of the same measurement. Ptychography exploits the overlap between neighbouring probe positions: the extended ptychographic iterative engine alternately enforces the measured Fourier amplitudes and the consistency of overlapping regions, updating both object and probe. Its resolution is set by the largest scattering angle recorded, not by the aperture, so it can exceed twice the convergence angle. Multislice ptychography represents the specimen as a stack of thin transmission functions joined by Fresnel propagators, and back-propagates each update through the stack. Its depth resolution scales as lambda over alpha squared.`,
  'mode-diff': `Diffraction, in more depth. At three hundred kilovolts the Ewald sphere has a radius of one over lambda, about fifty inverse ångströms, so it is almost flat, and a zone-axis pattern is nearly a planar section through the reciprocal lattice. A thin crystal elongates each reciprocal lattice point into a rod, with length proportional to one over the thickness, so spots appear even when the Bragg condition is not met exactly. The deviation is the excitation error, s. Kinematically, the intensity of a reflection is the structure factor squared, times a sinc-squared function of pi t s. The structure factor sums the atomic scattering factors with phases two pi g dot r, which is why some reflections are forbidden. In practice electrons scatter many times, coupling the beams dynamically over a length called the extinction distance. Kikuchi lines come from electrons that were first scattered inelastically and diffusely, then Bragg diffracted. They sit at plus and minus the Bragg angle about each lattice plane, so they move rigidly with the crystal.`,
  'mode-cbed': `Convergent beam diffraction, in more depth. With a convergence angle smaller than the Bragg angle, the disks do not overlap, and each point inside a disk corresponds to a different incident direction, and so a different excitation error. In the two-beam approximation the diffracted intensity oscillates as sine squared of pi t times the effective excitation error, the square root of s squared plus one over the extinction distance squared. These are the Kossel–Möllenstedt fringes. Plotting the fringe positions, s over n all squared, against one over n squared gives a straight line, whose intercept is one over the thickness squared. Higher-order Laue zone lines arise where the Ewald sphere cuts reciprocal lattice layers far from the origin. Their positions depend on the ratio of the lattice parameter to the wavelength, so a shift of one part in ten thousand is measurable, and they map strain. The symmetry within and between disks reveals the point group and space group, including dark Gjønnes–Moodie lines from screw axes and glide planes.`,
  'mode-eds': `X-ray spectroscopy, in more depth. The ionisation cross-section rises from the edge with overvoltage, roughly as the logarithm of U over U, following Bethe. Once a shell is ionised, the atom relaxes either by emitting an X-ray or an Auger electron; the fluorescence yield is only a few tenths of a percent for carbon, but about seventy percent for zirconium K lines. Line energies follow Moseley's law, scaling as Z minus one, squared. A silicon detector converts each photon into electron–hole pairs, about three point six electron volts each, and the Fano factor, about point one two, limits the peak width to roughly a hundred and twenty-five electron volts at manganese K alpha. Beneath the peaks lies the bremsstrahlung continuum, which ends at the Duane–Hunt limit, the beam energy. In a thin film, concentration ratios follow the Cliff–Lorimer equation: intensity ratio times a k-factor. Thicker films need absorption corrections, and the beam broadens as thickness to the three halves.`,
  'mode-eels': `Energy-loss spectroscopy, in more depth. Inelastic scattering is strongly forward-peaked, within a characteristic angle of roughly the energy loss divided by twice the beam energy, so a spectrometer collects most of it. The plasmon energy is h-bar times the plasma frequency, the square root of the valence electron density times e squared, over epsilon nought times the electron mass. The ratio of total to zero-loss intensity gives the thickness in units of the inelastic mean free path, through a simple logarithm. Core-loss edges sit on a background that falls as a power law in energy; after subtracting it, the edge's integrated intensity, divided by the low-loss intensity and a partial cross-section, gives the absolute number of atoms per unit area. Because the transition obeys the dipole selection rule, delta l equals plus or minus one, the near-edge fine structure maps the unoccupied density of states, so titanium L edges show crystal-field splitting, and white-line ratios reveal valence. With a monochromator, the zero-loss peak narrows to a few milli-electron volts, enough to see phonons.`,
  'mode-ronch': `The Ronchigram, in more depth. With the probe focused near a thin amorphous film, the far-field pattern is a shadow image of the specimen, and its local magnification is set by the curvature of the aberration function, chi. Where that curvature vanishes, magnification diverges, producing rings of infinite radial and azimuthal magnification from spherical aberration near Gaussian focus. Near the axis, the region where chi varies by less than pi over four, the Rayleigh quarter-wave criterion, appears smooth and featureless. Its radius is the largest usable convergence angle. The aberration function is expanded in powers of angle: defocus C1, two-fold astigmatism A1, axial coma B2, three-fold astigmatism A2, spherical aberration C3, four-fold astigmatism A3, and onward to fifth order. Tuning algorithms estimate these coefficients from the local magnification of small patches of the Ronchigram, or from a tableau of tilted-beam images, then adjust the multipole currents. Scherzer's theorem says round lenses alone can never cancel C3, which is why non-round multipoles are needed.`,

  // ---------------------------------------------------------------- components
  'Electron gun': `The electron gun, in more depth. A Schottky emitter is a heated thermionic source whose work-function barrier is lowered, by the Schottky effect, by an amount proportional to the square root of the applied field. Current density follows the Richardson–Dushman law with that lowered barrier. The figure of merit is the reduced brightness: current per unit area per unit solid angle, divided by the voltage. By Liouville's theorem it is conserved down the column, so probe current scales as brightness, times probe diameter squared, times convergence angle squared. The energy spread comes from the thermal distribution of emitted electrons, broadened further by Coulomb interactions near crossovers, the Boersch effect. Cold field emitters rely on Fowler–Nordheim tunnelling at room temperature, giving higher brightness and about half the energy spread, but they need ultra-high vacuum and periodic flashing.`,
  'High-voltage accelerator': `The accelerator, in more depth. At these energies electrons are relativistic, so the wavelength is Planck's constant over the square root of two m-nought e V, times one plus e V over two m-nought c squared. At three hundred kilovolts that gives one point nine seven picometres, with gamma about one point five nine. The interaction constant, sigma, falls with voltage, so a given specimen produces a smaller phase shift and weaker contrast at high voltage. The maximum energy transferred to a nucleus in a head-on collision grows with beam energy; for carbon in graphene, with a displacement threshold near seventeen electron volts, knock-on damage begins around eighty-six kilovolts. High-voltage ripple enters the focal spread through the relative voltage instability, which is why stabilisation below one part per million matters for the information limit.`,
  'Condenser lens 1': `The first condenser, in more depth. In a magnetic round lens, the focal power is proportional to the integral of the axial field squared along the axis, divided by the relativistically corrected voltage. Electrons also rotate, by an angle proportional to the integral of the field itself. The first condenser forms a demagnified image of the source; its strength sets the source size seen by the rest of the column, and through brightness conservation, the trade-off between current and spatial coherence. Because the soft-iron pole pieces show magnetic hysteresis, lens settings are reproducible only after normalisation, cycling the current through saturation. Lens current instability adds twice its relative value to the focal spread, because focal length depends on current squared.`,
  'Condenser lens 2': `The second condenser, in more depth. Together with the pre-field of the objective lens, it sets where the illumination crosses over. Placing the crossover at the front focal plane of the pre-field produces parallel illumination for imaging and diffraction; moving it toward the specimen produces a converging probe. The convergence semi-angle, together with the effective source size, sets the partial spatial coherence of the illumination, which damps the contrast transfer function through an envelope that depends on the slope of the aberration function.`,
  'Condenser aperture': `The condenser aperture, in more depth. The probe diameter is roughly the quadrature sum of four terms: the demagnified source; the diffraction limit, about one point two two lambda over alpha; the spherical-aberration disk, about half C-s alpha cubed; and the chromatic disk, C-c times the relative energy spread times alpha. Diffraction favours a large aperture, aberrations a small one, giving an optimum that scales as lambda over C-s to the one quarter. At fixed brightness, current scales as alpha squared, so the aperture also sets the dose. Off-centre apertures introduce coma, and contamination on the aperture edge can charge and deflect the beam.`,
  'Aberration corrector': `The aberration corrector, in more depth. Scherzer showed in nineteen thirty-six that any rotationally symmetric, static, space-charge-free electron lens has positive spherical and chromatic aberration. Correctors escape the theorem by breaking rotational symmetry. In the hexapole design of Rose and Haider, two strong hexapoles are linked by a transfer doublet: their primary three-fold aberrations cancel, but a secondary, rotationally symmetric negative third-order aberration remains, and that cancels the objective's C-s. The quadrupole–octupole design of Krivanek uses octupoles directly, and can also correct chromatic aberration. Correction exposes higher orders, such as fifth-order C5 and six-fold astigmatism, and parasitic aberrations from misalignment drift over time, so correctors are re-tuned from Ronchigrams or tilt tableaus, with multipole currents stable to parts per million.`,
  'Scan coils': `The scan coils, in more depth. Two deflection stages, with opposite sense, shift the beam while keeping it passing through a fixed pivot point, ideally the coma-free point of the objective, so that the beam's angle stays constant as it scans. Image fidelity depends on calibration against a known lattice spacing, on scan rotation relative to the specimen, and on flyback: the coils' inductance means the beam needs time to settle at the start of each line, producing distortion. Specimen drift during a slow frame shears the image, which is why fast, repeated frames, or pairs of orthogonal scans, are aligned and averaged for precise measurement of atom positions.`,
  'Objective lens': `The objective lens, in more depth. The specimen is immersed in a field of about two tesla between the pole pieces, so the lens acts as both a condenser pre-field and an imaging post-field. Typical uncorrected values are a focal length of about two millimetres, a spherical aberration coefficient around one millimetre, and a chromatic coefficient around one point two millimetres. A wider pole-piece gap allows more specimen tilt and room for detectors, at the cost of larger aberrations. The chromatic coefficient converts the energy spread, high-voltage ripple, and lens-current ripple into a focal spread, delta, which sets the information limit. Alignment uses the current or voltage centre and coma-free tilts, so the optical axis passes through the field centre.`,
  'EDS X-ray detector': `The X-ray detector, in more depth. A silicon drift detector is a fully depleted silicon wafer with concentric drift rings that funnel charge to a tiny central anode. The small anode capacitance gives low noise at short shaping times, so it handles hundreds of thousands of counts per second with Peltier cooling instead of liquid nitrogen. Energy resolution combines electronic noise with the Fano-limited statistics of pair creation. The collection solid angle, area over distance squared, typically from a tenth to over one steradian, sets sensitivity, since X-rays are emitted isotropically. Spectra contain artefacts: escape peaks one point seven four kilo-electron volts below major lines, sum peaks at high rates, an internal silicon fluorescence peak, and spurious system peaks from the holder and pole pieces.`,
  'Objective aperture': `The objective aperture, in more depth. In the back focal plane, radius maps directly to scattering angle, and to spatial frequency k equals theta over lambda. An aperture therefore acts as a low-pass filter on the exit wave, removing frequencies beyond its edge and converting scattering out of the aperture into amplitude contrast: diffraction contrast in crystals, and mass–thickness contrast in amorphous material. For dark-field imaging, the beam is tilted so that the selected reflection travels along the optic axis, avoiding the extra aberrations of off-axis rays. Phase plates, such as Zernike or Volta designs, also sit in this plane, shifting the unscattered beam by a quarter wave to give in-focus phase contrast.`,
  'Back focal plane': `The back focal plane, in more depth. The wave here is the Fourier transform of the exit wave, with position in the plane equal to the focal length times lambda times spatial frequency. Lens aberrations act as a phase factor multiplying the wave in this plane, which is why the contrast transfer function is defined in reciprocal space. In a crystal, each Bragg reflection with reciprocal lattice vector g arrives at its own point, so the plane holds the diffraction pattern, and apertures placed here select which frequencies or reflections contribute to the image.`,
  'Selected-area aperture': `The selected-area aperture, in more depth. It sits in the first image plane, where the image is magnified about twenty-five to fifty times, so a ten-micron aperture selects a region of a few hundred nanometres on the specimen. Spherical aberration and defocus limit the selection: a beam scattered through angle theta appears displaced in the image plane by about C-s theta cubed plus defocus times theta, so high-order reflections can come from outside the selected area. This limits conventional selected-area diffraction to regions of roughly half a micron; smaller regions need nanobeam or convergent beam methods.`,
  'Intermediate lens': `The intermediate lens, in more depth. Its excitation decides which plane is conjugate to the detector: the image plane for imaging, or the back focal plane for diffraction. In diffraction, the effective camera length relates a distance on the detector to a scattering angle, and it is calibrated using a standard such as polycrystalline gold or silicon. The image rotates as excitation changes, so the rotation between image and diffraction pattern must be calibrated, and projector distortions, often elliptical at the one percent level, must be corrected before measuring strain from diffraction patterns.`,
  'Projector lens': `The projector, in more depth. The final lenses supply most of the total magnification. Because the angular aperture of the image is tiny at high magnification, the depth of focus is enormous, so detectors at different heights all see a sharp image. Projector lenses introduce radial and spiral distortion, which can reach a few percent at low magnification. Magnification is calibrated against cross-grating replicas at low magnification and against crystal lattice spacings at high magnification, typically to about two percent.`,
  'Fluorescent screen': `The fluorescent screen, in more depth. A zinc sulfide or similar phosphor converts electron energy to green light, matched to the eye's peak sensitivity. Its spatial resolution, tens of microns, is set by electron scattering in the phosphor layer, so fine details are judged through binoculars at high magnification. The screen is also an electrometer: the current it collects, divided by its area and the magnification squared, gives the current density at the specimen, the basis for estimating electron dose. Lead glass in the viewing window absorbs the X-rays generated where the beam strikes.`,
  'Annular dark-field detector': `The annular dark-field detector, in more depth. A scintillator, read by a photomultiplier, collects electrons between an inner and an outer angle. When the inner angle is about three times the convergence angle or larger, typically above sixty milliradians, the signal is dominated by incoherent thermal diffuse scattering, and image contrast scales strongly with atomic number. Changing the camera length changes the collection angles: a low inner angle gives low-angle annular dark field, which is sensitive to strain and channelling. For quantitative work, the detector's response is mapped and the image is normalised to the incident beam intensity, so that counts can be compared with simulations column by column.`,
  'Bright-field detector': `The bright-field detector, in more depth. By the reciprocity theorem, a STEM detector of a given angular size is equivalent to a TEM illumination of the same angle, so a small on-axis detector produces coherent phase contrast with the same transfer function as conventional imaging. Annular bright field uses a ring inside the bright-field disk, roughly from half the convergence angle to the full angle. There, channelling along light-element columns redistributes intensity in a way that makes oxygen, nitrogen, and even lithium and hydrogen columns visible as dark dots, fairly robust to thickness and defocus.`,
  'Direct electron detector': `The direct electron detector, in more depth. Monolithic active-pixel sensors detect each electron directly in a thin silicon layer; in counting mode, each event is reduced to a single count, often with sub-pixel centroiding, raising the detective quantum efficiency close to one at low spatial frequency. Their limit is coincidence loss, two electrons in one pixel in one frame, so they suit low dose rates. Hybrid pixel detectors pair a thicker sensor with a separate counting chip for every pixel, giving very high dynamic range for diffraction patterns, at larger pixel sizes. Frame rates from one to over a hundred kilohertz make 4D-STEM practical. Backscattering within the sensor broadens the point spread, especially at three hundred kilovolts.`,
  'Magnetic prism': `The magnetic prism, in more depth. In a uniform field, an electron follows a circle with radius equal to its relativistic momentum divided by e B, so electrons that lost energy follow tighter arcs. The prism also focuses, imaging the spectrometer entrance onto a dispersion plane with a dispersion of a few microns per electron volt. Multipole lenses after the prism correct second- and third-order aberrations, so the spectrum stays sharp over a wide energy range and energy-filtered images stay undistorted. The entrance aperture sets the collection semi-angle, beta, which must be known for quantification. Any drift in high voltage appears directly as a shift of the spectrum.`,
  'Energy-loss spectrum': `The energy-loss spectrum, in more depth. Below about fifty electron volts, the low-loss region contains plasmons, interband transitions, and the band gap; Kramers–Kronig analysis converts it into the complex dielectric function. Multiple scattering mixes plasmons with core edges, so spectra are deconvolved with the Fourier-log or Fourier-ratio methods. Each core-loss edge needs a power-law background fit before integration. Edge onsets shift by a few electron volts with oxidation state, the chemical shift, and the ratio of the L-three to L-two white lines in transition metals tracks valence. Extended fine structure, tens to hundreds of electron volts above the edge, encodes nearest-neighbour distances, like X-ray absorption spectroscopy.`,
};

export const NARRATION = { general: GENERAL, physics: PHYSICS };
export const LEVELS = [['general', 'General'], ['physics', 'Physics']];
// ElevenLabs premade voices: Alice (British, clear) and George (British, warm).
export const VOICES = { female: { label: 'Female', id: 'Xb7hH8MSUJpSbSDYk0k2' }, male: { label: 'Male', id: 'JBFqnCBsd6RMkjVDRZzb' } };

// ---------------------------------------------------------------- settings
const store = (k, v) => { try { if (v === undefined) return localStorage.getItem(k); localStorage.setItem(k, v); } catch {} return null; };
const settings = { level: store('tem-narr-level') === 'physics' ? 'physics' : 'general', voice: store('tem-narr-voice') === 'female' ? 'female' : 'male' };
export const getSettings = () => ({ ...settings });
export function setSettings(o) {
  const was = current;
  Object.assign(settings, o);
  store('tem-narr-level', settings.level); store('tem-narr-voice', settings.voice);
  if (was) speak(was); // restart what was playing in the new level or voice
}

// ---------------------------------------------------------------- playback
// Pre-generated ElevenLabs clips when present, browser speech otherwise.
const BASE = 'audio/narration/';
let manifest = null;
const manifestReady = fetch(BASE + 'manifest.json').then((r) => (r.ok ? r.json() : {})).catch(() => ({})).then((m) => (manifest = m));

let audio = null, utter = null, current = null;
const listeners = new Set();
const emit = () => listeners.forEach((f) => f(current));
export const onNarration = (f) => listeners.add(f);
export const playing = () => current;

export function stop() {
  if (audio) { audio.pause(); audio = null; }
  if (utter && 'speechSynthesis' in window) speechSynthesis.cancel();
  utter = null;
  current = null;
  emit();
}

const FEMALE = /Samantha|Karen|Moira|Tessa|Serena|Victoria|Fiona|Kate|Susan|Zira|Aria|Jenny|Libby|Sonia|Female|Google UK English Female|Google US English/i;
const MALE = /Daniel|Alex|Fred|Oliver|Arthur|Tom|Aaron|Rishi|Guy|Ryan|David|Mark|George|Male|Google UK English Male/i;
function browserVoice(gender) {
  const vs = speechSynthesis.getVoices().filter((x) => /^en[-_]/.test(x.lang));
  const re = gender === 'male' ? MALE : FEMALE, other = gender === 'male' ? FEMALE : MALE;
  return vs.find((x) => re.test(x.name) && !other.test(x.name)) || vs.find((x) => re.test(x.name)) || vs[0];
}

export async function speak(id) {
  stop();
  const { level, voice } = settings;
  const text = NARRATION[level][id];
  if (!text) return;
  current = id;
  emit();
  await manifestReady;
  if (current !== id) return;
  const file = manifest?.[`${voice}/${level}/${id}`];
  if (file) {
    const a = new Audio(BASE + file);
    audio = a;
    a.onended = () => { if (audio === a) { audio = null; current = null; emit(); } };
    try { await a.play(); return; } catch { audio = null; if (current !== id) return; }
  }
  if (!('speechSynthesis' in window)) { current = null; emit(); return; }
  const u = new SpeechSynthesisUtterance(text);
  const v = browserVoice(voice);
  if (v) u.voice = v;
  u.onend = () => { if (utter === u) { utter = null; current = null; emit(); } };
  utter = u;
  speechSynthesis.speak(u);
}

export const toggle = (id) => (current === id ? stop() : speak(id));
